### PR TITLE
Fix worker creation in graphite backend

### PR DESCRIPTION
**Pull request by hodgestar**

### CODE REVIEW

**Comment by hodgestar** [comment]
Ready for review. Would still like to understand why tests passed.

**Comment by justinvdm** [comment]
:+1:

@hodgestar could you explain what was broken and how this fixed it?

**Comment by hodgestar** [comment]
`worker_creator` was defined in `__init__` but used in `create_worker`.

**Comment by justinvdm** [comment]
Doh, ofc, sorry diff confused me.

**Comment by hodgestar** [comment]
Tests updated. Ready for another review.

**Comment by justinvdm** [comment]
:+1:

**Pull request merged**
